### ISSUE TITLE
Peer feedback_Lilliana

### ISSUE THREAD

**Issue by lnishihira** [zenyui/ga-portfolio#4]
We know that a problem you're having is highly correlated features. 
One way you can deal with getting rid of some features is to standardize each monetary feature to make them comparable, therefore making the most of each feature. You can then get rid of redundant features. 

If the average transaction at the sandwich or gelato register is $10 when someone spends $30 that's much more significant than if they spend $30 at the produce checkout, where the average may be $80. 

An alternative to this is maybe you don't even care how much money they've spent but only if they spent money at all (0 or 1) and where in the store they spent money. Maybe this way you can find out that if they buy gelato first, they're more likely to buy more in the long run as opposed to buying tomato sauce first. 

I do still think it is worth if to split up the data by before 5PM and after 5PM but maybe this is just a good technique to again re-work the data. You can do a time-series of customer repeats by each time of day. Maybe the people who get lunch more quickly come back then the ones that buy produce, or maybe the opposite. 

I would assume that the products, like homemade pasta that are uniquely accessible at eataly to be the products that make people come back. I personally think it would be very interesting to understand the products and the physical place in the store that make someone come back.  

If you want to write down to us which of your features are over-correlated with eachother we can talk about how to get rid of some of them w/o losing the information.

**Comment by zenyui** [comment]
thanks.  all good ideas.  I think you're right that I have to split my data by time of day and run separate models.  i'll let you know how it goes
