### ISSUE TITLE
Feedback Ro

### ISSUE THREAD

**Issue by rogeliozunigarubio** [zenyui/ga-portfolio#6]
I really like your project question, I think it has great potential to be setup in a pipeline for continued future use in production to guide and monitor changes to the shopping environment at Eataly.

Like we talked about in person, you may be able to improve predictability by adding new time-of-day based features like "lunch-time" and "dinner".

On the concept of "high-rollers" being kept in the data set, I think they are actually not helpful to your ultimate question and it may be worth considering removing them, or using them as a separate model, they clearly don't fit your category of either repeat or non-repeat since they become a skew once they are loyal customers.

Another tiny nit-picky improvement is to give meaningful labels to the graphs, they are so great (nice colors!) and yet that last touch of having the days of the week in word format instead of numbers would make it perfect (same for most of the graphs)

**Comment by zenyui** [comment]
thanks.  definitely going to split the data set into time of day.  I'll try removing the "high-rollers" from the data set to see how that impacts clustering and predictive performance, but clustering may naturally segregate them anyways.

i'll definitely label the graphs more.  i am going to split all of that into an EDA notebook, but you're right that they have to be more clear.
